# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

#####
# build dist/magic-print.js
#####

SDLC_MAGIC_PRINT_JS:=$(DIST)/magic-print.js
SDLC_MAGIC_PRINT_JS_ENTRY=$(SRC)/lib/index.mjs
BUILD_TARGETS+=$(SDLC_MAGIC_PRINT_JS)

$(SDLC_MAGIC_PRINT_JS): package.json $(SDLC_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(SDLC_MAGIC_PRINT_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)

#####
# end dist/magic-print.js
#####
